---
- name: Deploy site config
  ansible.builtin.template:
    src: app.conf.j2
    dest: /etc/nginx/conf.d/app.conf

- name: Restart nginx
  ansible.builtin.systemd_service:
    name: nginx
    state: restarted
